"use strict";

const dotenv = require("dotenv");
const SERVICE_ACCOUNT_EMAIL = require("./GCP_SERVICE_ACCOUNT_EMAIL");
dotenv.config();

module.exports = {
  API_URI: require("./API_URI"),
  API_PORT: require("./API_PORT"),
  AUTH_URI: require("./AUTH_URI"),
  ...require("./WEBSITE_DOMAIN"),
  SHARED_DB_URI: require("./MONGODB_URI"),
  NODE_ENV: require("./NODE_ENV"),
  RELEASE_ENV: require("./RELEASE_ENV"),
  // MAIL: require('./SMTP'),
  SENDGRID_API_KEY: require('./SENDGRID_API_KEY'),
  SMS_COUNTRY_AUTH_KEY: require('./SMS_COUNTRY_AUTH_KEY'),
  SMS_COUNTRY_AUTH_TOKEN: require('./SMS_COUNTRY_AUTH_TOKEN'),
  SMS_COUNTRY_URI: require('./SMS_COUNTRY_URI'),
  SMS_COUNTRY_CONCATENATED_KEY: require('./SMS_COUNTRY_CONCATENATED_KEY'),

  TAQNYAT_URI: require('./TAQNYAT_URI'),
  TAQBYAT_BEARER_TOKEN: require('./TAQBYAT_BEARER_TOKEN'),
  TAQNYAT_SENDER: require('./TAQNYAT_SENDER'),

  S3_ACCESS_KEY_ID: require("./S3_ACCESS_KEY_ID"),
  S3_BUCKET: require("./S3_BUCKET"),
  S3_ENDPOINT: require("./S3_ENDPOINT"),
  S3_REGION: require("./S3_REGION"),
  S3_SECRET_ACCESS_KEY: require("./S3_SECRET_ACCESS_KEY"),
  S3_CDN_URL: require("./S3_CDN_URL"),

  FIREBASE_ADMIN: require('./FIREBASE'),

  WHATSAPP_URI: require('./WHATSAPP_URI'),
  WHATSAPP_HEADER_TOKEN: require('./WHATSAPP_HEADER_TOKEN'),

  DEV_ADAVERSE_NFT_URL: require('./DEV_ADAVERSE_NFT_URL'),
  DEV_ADAVERSE_NFT_KEY: require('./DEV_ADAVERSE_NFT_KEY'),
  MITHU_NFT_MINT_ADDRESS: require('./MITHU_NFT_MINT_ADDRESS'),

  WEBSOCKET_URL: require('./WEBSOCKET_URL'),

  //APPLE WALLET
  APPLE_WALLET_WEBSERVICE_URL: require('./APPLE_WALLET_WEBSERVICE_URL'),
  APPLE_TEAM_IDENTIFIER: require('./APPLE_TEAM_IDENTIFIER'),
  APPLE_ORGANIZATION_NAME: require('./APPLE_ORGANIZATION_NAME'),
  APPLE_PASS_TYPE_IDENTIFIER: require('./APPLE_PASS_TYPE_IDENTIFIER'),
  APPLE_APN_KEY_ID: require('./APPLE_APN_KEY_ID'),
  APPLE_APN_KEY_NAME: require('./APPLE_APN_KEY_NAME'),
  APPLE_APN_KEY_PATH: require('./APPLE_APN_KEY_PATH'),
  APPLE_NFC_PUBLIC_KEY: require('./APPLE_NFC_PUBLIC_KEY'),

  //GOOGLE WALLET
  GCP_APPLICATION_CREDENTIALS: require('./GCP_APPLICATION_CREDENTIALS'),
  GCP_ISSUER_ID: require('./GCP_ISSUER_ID'),
  GCP_SERVICE_ACCOUNT_EMAIL: require('./GCP_SERVICE_ACCOUNT_EMAIL'),
  GOOGLE_WALLET_PASS_WEBHOOK_CALLBACK: require('./GOOGLE_WALLET_PASS_WEBHOOK_CALLBACK'),
  GOOGLE_WALLET_PASS_LOGO_IMAGE_URL: require('./GOOGLE_WALLET_PASS_LOGO_IMAGE_URL'),
  GOOGLE_WALLET_PASS_HERO_IMAGE_URL: require('./GOOGLE_WALLET_PASS_HERO_IMAGE_URL'),
};
